spring:
  application:
    name: common-module
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-6702530.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            client-id: 0oaxtfbpz4KhTFqmu697
            client-secret: fSXozMyAuzuncC8Q5-sQCEwYxSmTNj_1vj
#            scope: openid, profile, email, offline_access
            scope: service.access
            authorization-grant-type: client_credentials
        #            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          okta:
            issuer-uri: https://integrator-6702530.okta.com/oauth2/default
resilency4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        event-consumer-buffer-size: 10
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      paymentServiceCircuitBreaker:
        event-consumer-buffer-size: 10
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3